// Portal vortex (nt-rewrite objects SpiralCont/Spiral + scrDrawSpiral.gml)
// rendered as ONE procedural quad. Each wisp is a transformed sample of the
// real spiral art; growth/alpha/lightning follow the GameMaker laws:
//   grow += 0.0002 (+0.0003 Proto); xscale += grow;
//   grow = (grow+1)*(1+0.0005*xscale)-1
//   white pass (c_white) then black 0.8-xscale, destroy xscale>2.5
//   (oversized wisps survive while lightning lanim is in 0..6)
//   lightning lanim -random(300) + 0.2+random(0.3) per tick
//   draw order oldest-first, so the NEWEST wisp lands on top
// Rotation convention: GML angles are CCW-positive in y-down storage, so
// sampling inverts with (xc-ys, xs+yc) - the transpose would mirror the spin.
#import bevy_sprite::mesh2d_vertex_output::VertexOutput

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> wisps: array<vec4<f32>, 128>;
@group(#{MATERIAL_BIND_GROUP}) @binding(1) var<uniform> glob_a: vec4<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(2) var<uniform> glob_b: vec4<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(3) var spiral_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(4) var spiral_smp: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(5) var bolt_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(6) var bolt_smp: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(7) var<uniform> debris: array<vec4<f32>, 32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(8) var debris_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(9) var debris_smp: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(10) var spiral_proto_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(11) var spiral_proto_smp: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(12) var spiral_idpd_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(13) var spiral_idpd_smp: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(14) var spiral_idpd2_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(15) var spiral_idpd2_smp: sampler;

const N: u32 = 128u;
const BOLT_FRAMES: f32 = 6.0;

// Exact GML growth table 0..119 (xscale at tick age, before death at >2.5).
// Generated by iterating the GML recurrence. Lerp for fractional ages.
const SCALE_TABLE: array<f32, 120> = array<f32, 120>(
    0.000000, 0.000200, 0.000600, 0.001201, 0.002002, 0.003004, 0.004207, 0.005613,
    0.007221, 0.009033, 0.011050, 0.013272, 0.015700, 0.018337, 0.021183, 0.024239,
    0.027508, 0.030990, 0.034688, 0.038604, 0.042738, 0.047095, 0.051674, 0.056480,
    0.061514, 0.066779, 0.072278, 0.078013, 0.083987, 0.090204, 0.096665, 0.103376,
    0.110338, 0.117557, 0.125034, 0.132774, 0.140781, 0.149059, 0.157613, 0.166445,
    0.175562, 0.184967, 0.194666, 0.204663, 0.214963, 0.225572, 0.236495, 0.247737,
    0.259305, 0.271204, 0.283440, 0.296019, 0.308948, 0.322234, 0.335883, 0.349902,
    0.364299, 0.379081, 0.394254, 0.409828, 0.425810, 0.442209, 0.459032, 0.476288,
    0.493987, 0.512137, 0.530748, 0.549829, 0.569390, 0.589442, 0.609994, 0.631057,
    0.652643, 0.674762, 0.697426, 0.720646, 0.744435, 0.768805, 0.793769, 0.819340,
    0.845531, 0.872355, 0.899828, 0.927963, 0.956775, 0.986279, 1.016491, 1.047426,
    1.079101, 1.111533, 1.144739, 1.178736, 1.213543, 1.249177, 1.285658, 1.323006,
    1.361239, 1.400380, 1.440448, 1.481465, 1.523453, 1.566435, 1.610434, 1.655473,
    1.701577, 1.748772, 1.797082, 1.846534, 1.897155, 1.948972, 2.002015, 2.056312,
    2.111892, 2.168787, 2.227029, 2.286648, 2.347680, 2.410156, 2.474113, 2.539587
);

fn wisp_scale(age: f32) -> f32 {
    if (age <= 0.0) { return 0.0; }
    if (age >= 119.0) { return SCALE_TABLE[119]; }
    let i = u32(age);
    let f = fract(age);
    return mix(SCALE_TABLE[i], SCALE_TABLE[i + 1u], f);
}

// Proto growth (grow base 0.0005 from `random(0.01)` mean head-start 0.005).
// Same recurrence/baking as SCALE_TABLE, reaches 2.5 around tick 86.
const PROTO_TABLE: array<f32, 120> = array<f32, 120>(
    0.005500, 0.006503, 0.008009, 0.010019, 0.012534, 0.015555, 0.019084, 0.023123,
    0.027673, 0.032737, 0.038318, 0.044418, 0.051040, 0.058188, 0.065866, 0.074076,
    0.082824, 0.092113, 0.101949, 0.112337, 0.123281, 0.134788, 0.146862, 0.159512,
    0.172741, 0.186559, 0.200971, 0.215984, 0.231608, 0.247849, 0.264716, 0.282218,
    0.300363, 0.319161, 0.338622, 0.358755, 0.379571, 0.401081, 0.423296, 0.446227,
    0.469887, 0.494287, 0.519440, 0.545359, 0.572058, 0.599551, 0.627852, 0.656975,
    0.686937, 0.717752, 0.749438, 0.782010, 0.815485, 0.849883, 0.885219, 0.921514,
    0.958786, 0.997056, 1.036343, 1.076669, 1.118055, 1.160523, 1.204096, 1.248797,
    1.294650, 1.341681, 1.389914, 1.439375, 1.490092, 1.542091, 1.595402, 1.650052,
    1.706073, 1.763495, 1.822349, 1.882668, 1.944485, 2.007835, 2.072752, 2.139272,
    2.207434, 2.277274, 2.348832, 2.422149, 2.497266, 2.574225, 2.653071, 2.733847,
    2.816601, 2.901380, 2.988232, 3.077208, 3.168360, 3.261740, 3.357404, 3.455407,
    3.555807, 3.658663, 3.764036, 3.871990, 3.982589, 4.095900, 4.211991, 4.330932,
    4.452796, 4.577658, 4.705594, 4.836684, 4.971010, 5.108655, 5.249706, 5.394252,
    5.542384, 5.694199, 5.849793, 6.009267, 6.172725, 6.340273, 6.512023, 6.688088
);

fn proto_scale(age: f32) -> f32 {
    if (age <= 0.0) { return 0.0; }
    if (age >= 119.0) { return PROTO_TABLE[119]; }
    let i = u32(age);
    let f = fract(age);
    return mix(PROTO_TABLE[i], PROTO_TABLE[i + 1u], f);
}

// Per-wisp lightning clock (`lanim = -random(300) + (0.2+random(0.3))*age).
fn wisp_lanim(birth: f32, age: f32) -> f32 {
    let seed0 = hash11(birth, 1.0);
    let seed1 = hash11(birth, 3.0);
    return -seed0 * 300.0 + (0.2 + seed1 * 0.3) * age;
}

fn hash11(birth: f32, salt: f32) -> f32 {
    let x = sin(birth * 127.1 + salt * 311.7) * 43758.5453;
    return fract(x);
}

@fragment
fn fragment(mesh: VertexOutput) -> @location(0) vec4<f32> {
    let gui = vec2<f32>(mesh.uv.x * 320.0, (1.0 - mesh.uv.y) * 240.0);
    let tick_now = glob_a.x;
    let lightning_on = glob_a.y;
    let bg_alpha = glob_b.y;
    let thresh = glob_b.z;
    // SpiralKind discriminant + jungle-debris flag (see Rust glob_b docs).
    let kind = glob_b.w - floor(glob_b.w / 4.0) * 4.0;
    let debris_big = glob_b.w >= 4.0;
    var acc = vec3<f32>(glob_a.z, glob_a.w, glob_b.x);
    var out_alpha = bg_alpha;

    // Oldest drawn first, so the NEWEST wisp lands on top: GML `with`
    // iterates instances in creation order and script draws ignore depth.
    let base = u32(tick_now);
    for (var k: u32 = 0u; k < N; k = k + 1u) {
        let birth = base - (N - 1u - k);
        let d = wisps[birth % N];
        if (d.z < 0.0) { continue; }
        let age = tick_now - d.z;
        if (age < 0.0) { continue; }
        var s = wisp_scale(age);
        if (kind > 0.5 && kind < 1.5) {
            s = proto_scale(age);
        }
        // Spiral/Step_0: oversized wisps survive while lightning shows.
        let lanim = wisp_lanim(d.z, age);
        if (s > thresh && !(lanim > 0.0 && lanim < 6.0)) { continue; }

        // IDPD2 variant rides in the rot sign (CPU); art is 128px single.
        let idpd2 = d.w < 0.0;
        let rot = abs(d.w);
        let c = cos(rot);
        let sn = sin(rot);
        // Inverse-map into the frame (GML CCW-positive, y-down storage).
        var rel = gui - d.xy;
        rel = vec2<f32>(c * rel.x - sn * rel.y, sn * rel.x + c * rel.y);

        // Lightning pass FIRST (scrDrawSpiral draws the bolt before the
        // wisp's own white/black spiral passes cover it).
        if (lightning_on > 0.5 && s > 0.05) {
            if (lanim > 0.0 && lanim < 6.0) {
                let frame = clamp(floor(lanim), 0.0, BOLT_FRAMES - 1.0);
                let langle = hash11(d.z, 2.0) * 6.2831853;
                let lc = cos(rot + langle);
                let ls = sin(rot + langle);
                var lrel = gui - d.xy;
                lrel = vec2<f32>(lc * lrel.x - ls * lrel.y, ls * lrel.x + lc * lrel.y);
                let lbolt_half = vec2<f32>(88.0, 88.0) * s;
                let buv = (lrel + vec2<f32>(180.0 - 88.0, 0.0) * s) / (lbolt_half * 2.0) + vec2<f32>(0.5, 0.5);
                if (all(buv > vec2<f32>(0.0)) & all(buv < vec2<f32>(1.0))) {
                    let bolt_uv_x = (frame * 176.0 + 0.5 + buv.x * 175.0) / 1056.0;
                    let bolt_uv_y = (0.5 + buv.y * 175.0) / 176.0;
                    let btex = textureSampleLevel(bolt_tex, bolt_smp, vec2<f32>(bolt_uv_x, bolt_uv_y), 0.0);
                    // GML: white 1 then black 0.4 - s/2
                    acc = mix(acc, btex.rgb, btex.a);
                    out_alpha = max(out_alpha, btex.a);
                    let bolt_black = clamp(0.4 - s * 0.5, 0.0, 1.0);
                    if (bolt_black > 0.001) {
                        acc = mix(acc, vec3<f32>(0.0), btex.a * bolt_black);
                    }
                }
            }
        }

        if (kind > 1.5 && kind < 2.5) {
            // IDPD: single 128x128 frame, origin centre.
            let half_ext = 64.0 * s * 10.0;
            let suv = rel / half_ext * 0.5 + vec2<f32>(0.5, 0.5);
            if (all(suv > vec2<f32>(0.0)) & all(suv < vec2<f32>(1.0))) {
                let uv = (suv * 127.0 + 0.5) / 128.0;
                var tex = textureSampleLevel(spiral_idpd_tex, spiral_idpd_smp, uv, 0.0);
                if (idpd2) {
                    tex = textureSampleLevel(spiral_idpd2_tex, spiral_idpd2_smp, uv, 0.0);
                }
                acc = mix(acc, tex.rgb, tex.a);
                out_alpha = max(out_alpha, tex.a);
                let black_a = clamp(0.8 - s, 0.0, 1.0);
                if (black_a > 0.001) {
                    acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
                }
            }
            continue;
        }

        let suv = rel / (32.0 * s * 10.0) * 0.5 + vec2<f32>(0.5, 0.5);
        if (all(suv > vec2<f32>(0.0)) & all(suv < vec2<f32>(1.0))) {
            // Half-texel inset to avoid atlas bleeding (sprite is 64x64 in 128x64 strip)
            let uv_x = (0.5 + suv.x * 63.0) / 128.0;
            let uv_y = (0.5 + suv.y * 63.0) / 64.0;
            var tex = textureSampleLevel(spiral_tex, spiral_smp, vec2<f32>(uv_x, uv_y), 0.0);
            if (kind > 0.5 && kind < 1.5) {
                tex = textureSampleLevel(spiral_proto_tex, spiral_proto_smp, vec2<f32>(uv_x, uv_y), 0.0);
            }
            // GML two-pass: white (c_white, alpha tex.a) then black 0.8 - s
            acc = mix(acc, tex.rgb, tex.a);
            out_alpha = max(out_alpha, tex.a);
            let black_a = clamp(0.8 - s, 0.0, 1.0);
            if (black_a > 0.001) {
                acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
            }
        }
    }

    // SpiralDebris pass - drawn AFTER all wisps (scrDrawSpiral order), on top.
    // CPU supplies [x, y, rot_rad, frame + xscale/32]; x < -100 = empty slot.
    // Jungle debris (sprDebris105) uses 16px frames instead of 8px.
    for (var i: u32 = 0u; i < 32u; i = i + 1u) {
        let d = debris[i];
        if (d.x < -100.0) { continue; }
        // Jungle debris uses 16px frames, all other areas 8px.
        var fpx = 8.0;
        if (debris_big) {
            fpx = 16.0;
        }
        let xs = fract(d.w) * 32.0;
        let frame = floor(d.w);
        let half_ext = (fpx * 0.5) * xs;
        var rel = gui - d.xy;
        let c = cos(d.z);
        let sn = sin(d.z);
        rel = vec2<f32>(c * rel.x - sn * rel.y, sn * rel.x + c * rel.y);
        let duv = rel / half_ext * 0.5 + vec2<f32>(0.5, 0.5);
        if (all(duv > vec2<f32>(0.0)) & all(duv < vec2<f32>(1.0))) {
            // frames in a 4-wide horizontal strip, half-texel inset
            let uv_x = (frame * fpx + 0.5 + duv.x * (fpx - 1.0)) / (4.0 * fpx);
            let uv_y = (0.5 + duv.y * (fpx - 1.0)) / fpx;
            let tex = textureSampleLevel(debris_tex, debris_smp, vec2<f32>(uv_x, uv_y), 0.0);
            // scrDrawSpiral: white 1, then black (1 - xscale)
            acc = mix(acc, tex.rgb, tex.a);
            out_alpha = max(out_alpha, tex.a);
            let black_a = clamp(1.0 - xs, 0.0, 1.0);
            if (black_a > 0.001) {
                acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
            }
        }
    }
    return vec4<f32>(acc, out_alpha);
}
