// Portal vortex (nt-rewrite objects SpiralCont/Spiral + scrDrawSpiral.gml)
// rendered as ONE procedural quad. Each wisp is a transformed sample of the
// real sprSpiral.png art; growth/alpha/lightning follow the GameMaker laws:
//   grow += 0.0002; xscale += grow; grow = (grow+1)*(1+0.0005*xscale)-1
//   white pass (c_white) then black 0.8-xscale, destroy xscale>2.5
//   lightning lanim -random(300) + 0.2+random(0.3) per tick
//   depth = image_angle -> OLDEST on top
#import bevy_sprite::mesh2d_vertex_output::VertexOutput

@group(#{MATERIAL_BIND_GROUP}) @binding(0) var<uniform> wisps: array<vec4<f32>, 128>;
@group(#{MATERIAL_BIND_GROUP}) @binding(1) var<uniform> glob_a: vec4<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(2) var<uniform> glob_b: vec4<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(3) var spiral_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(4) var spiral_smp: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(5) var bolt_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(6) var bolt_smp: sampler;
@group(#{MATERIAL_BIND_GROUP}) @binding(7) var<uniform> debris: array<vec4<f32>, 32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(8) var debris_tex: texture_2d<f32>;
@group(#{MATERIAL_BIND_GROUP}) @binding(9) var debris_smp: sampler;

const N: u32 = 128u;
const BOLT_FRAMES: f32 = 6.0;

// Exact GML growth table 0..119 (xscale at tick age, before death at >2.5).
// Generated by iterating the GML recurrence. Lerp for fractional ages.
const SCALE_TABLE: array<f32, 120> = array<f32, 120>(
    0.000000, 0.000200, 0.000600, 0.001201, 0.002002, 0.003004, 0.004207, 0.005613,
    0.007221, 0.009033, 0.011050, 0.013272, 0.015700, 0.018337, 0.021183, 0.024239,
    0.027508, 0.030990, 0.034688, 0.038604, 0.042738, 0.047095, 0.051674, 0.056480,
    0.061514, 0.066779, 0.072278, 0.078013, 0.083987, 0.090204, 0.096665, 0.103376,
    0.110338, 0.117557, 0.125034, 0.132774, 0.140781, 0.149059, 0.157613, 0.166445,
    0.175562, 0.184967, 0.194666, 0.204663, 0.214963, 0.225572, 0.236495, 0.247737,
    0.259305, 0.271204, 0.283440, 0.296019, 0.308948, 0.322234, 0.335883, 0.349902,
    0.364299, 0.379081, 0.394254, 0.409828, 0.425810, 0.442209, 0.459032, 0.476288,
    0.493987, 0.512137, 0.530748, 0.549829, 0.569390, 0.589442, 0.609994, 0.631057,
    0.652643, 0.674762, 0.697426, 0.720646, 0.744435, 0.768805, 0.793769, 0.819340,
    0.845531, 0.872355, 0.899828, 0.927963, 0.956775, 0.986279, 1.016491, 1.047426,
    1.079101, 1.111533, 1.144739, 1.178736, 1.213543, 1.249177, 1.285658, 1.323006,
    1.361239, 1.400380, 1.440448, 1.481465, 1.523453, 1.566435, 1.610434, 1.655473,
    1.701577, 1.748772, 1.797082, 1.846534, 1.897155, 1.948972, 2.002015, 2.056312,
    2.111892, 2.168787, 2.227029, 2.286648, 2.347680, 2.410156, 2.474113, 2.539587
);

fn wisp_scale(age: f32) -> f32 {
    if (age <= 0.0) { return 0.0; }
    if (age >= 119.0) { return SCALE_TABLE[119]; }
    let i = u32(age);
    let f = fract(age);
    return mix(SCALE_TABLE[i], SCALE_TABLE[i + 1u], f);
}

fn hash11(birth: f32, salt: f32) -> f32 {
    let x = sin(birth * 127.1 + salt * 311.7) * 43758.5453;
    return fract(x);
}

@fragment
fn fragment(mesh: VertexOutput) -> @location(0) vec4<f32> {
    let gui = vec2<f32>(mesh.uv.x * 320.0, (1.0 - mesh.uv.y) * 240.0);
    let tick_now = glob_a.x;
    let lightning_on = glob_a.y;
    var acc = vec3<f32>(glob_a.z, glob_a.w, glob_b.x);

    // Oldest-on-top
    let base = u32(tick_now);
    for (var j: u32 = 0u; j < N; j = j + 1u) {
        let birth = base - j;
        let d = wisps[birth % N];
        if (d.z < 0.0) { continue; }
        let age = tick_now - d.z;
        if (age < 0.0) { continue; }
        let s = wisp_scale(age);
        if (s > 2.5) { continue; }

        let half_ext = 32.0 * s * 10.0;
        var rel = gui - d.xy;
        let c = cos(d.w);
        let sn = sin(d.w);
        rel = vec2<f32>(c * rel.x + sn * rel.y, -sn * rel.x + c * rel.y);

        // Lightning pass FIRST (scrDrawSpiral draws the bolt before the
        // wisp's own white/black spiral passes cover it).
        if (lightning_on > 0.5 && s > 0.05) {
            // Per-wisp random lanim start and speed (GML: -random(300), 0.2+random(0.3)/tick)
            let seed0 = hash11(d.z, 1.0);
            let seed1 = hash11(d.z, 3.0);
            let inc = 0.2 + seed1 * 0.3;
            let lanim = -seed0 * 300.0 + inc * age;
            if (lanim > 0.0 && lanim < 6.0) {
                let frame = clamp(floor(lanim), 0.0, BOLT_FRAMES - 1.0);
                let langle = hash11(d.z, 2.0) * 6.2831853;
                let lc = cos(d.w + langle);
                let ls = sin(d.w + langle);
                var lrel = gui - d.xy;
                lrel = vec2<f32>(lc * lrel.x + ls * lrel.y, -ls * lrel.x + lc * lrel.y);
                let lbolt_half = vec2<f32>(88.0, 88.0) * s;
                let buv = (lrel + vec2<f32>(180.0 - 88.0, 0.0) * s) / (lbolt_half * 2.0) + vec2<f32>(0.5, 0.5);
                if (all(buv > vec2<f32>(0.0)) & all(buv < vec2<f32>(1.0))) {
                    let bolt_uv_x = (frame * 176.0 + 0.5 + buv.x * 175.0) / 1056.0;
                    let bolt_uv_y = (0.5 + buv.y * 175.0) / 176.0;
                    let btex = textureSampleLevel(bolt_tex, bolt_smp, vec2<f32>(bolt_uv_x, bolt_uv_y), 0.0);
                    // GML: white 1 then black 0.4 - s/2
                    acc = mix(acc, btex.rgb, btex.a);
                    let bolt_black = clamp(0.4 - s * 0.5, 0.0, 1.0);
                    if (bolt_black > 0.001) {
                        acc = mix(acc, vec3<f32>(0.0), btex.a * bolt_black);
                    }
                }
            }
        }

        let suv = rel / half_ext * 0.5 + vec2<f32>(0.5, 0.5);
        if (all(suv > vec2<f32>(0.0)) & all(suv < vec2<f32>(1.0))) {
            // Half-texel inset to avoid atlas bleeding (sprite is 64x64 in 128x64 strip)
            let uv_x = (0.5 + suv.x * 63.0) / 128.0;
            let uv_y = (0.5 + suv.y * 63.0) / 64.0;
            let tex = textureSampleLevel(spiral_tex, spiral_smp, vec2<f32>(uv_x, uv_y), 0.0);
            // GML two-pass: white (c_white, alpha tex.a) then black 0.8 - s
            acc = mix(acc, tex.rgb, tex.a);
            let black_a = clamp(0.8 - s, 0.0, 1.0);
            if (black_a > 0.001) {
                acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
            }
        }
    }

    // SpiralDebris pass - drawn AFTER all wisps (scrDrawSpiral order), on top.
    // CPU supplies [x, y, rot_rad, frame + xscale/32]; x < -100 = empty slot.
    for (var i: u32 = 0u; i < 32u; i = i + 1u) {
        let d = debris[i];
        if (d.x < -100.0) { continue; }
        let xs = fract(d.w) * 32.0;
        let frame = floor(d.w);
        let half_ext = 4.0 * xs; // sprDebris0: 8x8 px, origin centre
        var rel = gui - d.xy;
        let c = cos(d.z);
        let sn = sin(d.z);
        rel = vec2<f32>(c * rel.x + sn * rel.y, -sn * rel.x + c * rel.y);
        let duv = rel / half_ext * 0.5 + vec2<f32>(0.5, 0.5);
        if (all(duv > vec2<f32>(0.0)) & all(duv < vec2<f32>(1.0))) {
            // 8x8 frames in a 32x8 strip, half-texel inset
            let uv_x = (frame * 8.0 + 0.5 + duv.x * 7.0) / 32.0;
            let uv_y = (0.5 + duv.y * 7.0) / 8.0;
            let tex = textureSampleLevel(debris_tex, debris_smp, vec2<f32>(uv_x, uv_y), 0.0);
            // scrDrawSpiral: white 1, then black (1 - xscale)
            acc = mix(acc, tex.rgb, tex.a);
            let black_a = clamp(1.0 - xs, 0.0, 1.0);
            if (black_a > 0.001) {
                acc = mix(acc, vec3<f32>(0.0), tex.a * black_a);
            }
        }
    }
    return vec4<f32>(acc, 1.0);
}
