name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: mlm-games/ci/.github/workflows/rust-app-ci.yml@main
    with:
      system-deps-linux: libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      run-clippy: false
      run-fmt: true
      run-test: true
      extra-rust-targets: wasm32-unknown-unknown,aarch64-linux-android
      extra-checks: |
        --target aarch64-linux-android --features bevy/android-native-activity
        --features physics
