name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    uses: mlm-games/ci/.github/workflows/rust-app-release.yml@main
    with:
      working-directory: .
      bin-name: my-ecosystem-bevy
      app-slug: my-ecosystem-bevy
      system-deps-linux: libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      include-web: true
      itch-username: mlm-games
      itch-game: my-ecosystem-bevy
    secrets: inherit
